using UnityEngine;

namespace qASIC.ProjectSettings
{
    [System.Serializable]
    [ExcludeFromPreset]
    public class DisplayerProjectSettings : ProjectSettingsBase
    {
        private static DisplayerProjectSettings _instance;
        public static DisplayerProjectSettings Instance => CheckInstance("Displayer", _instance);


        [InspectorLabel("Object Name")] public string debugObjectName = "Debug Displayer - autogenerated";
        [InspectorLabel("Displayer Name")] public string debugDisplayerName = "debug";

        [Header("Settings")]
        [InspectorLabel("Canvas Order")] public int debugCanvasOrder = 20;
        [InspectorLabel("Font size")] public int debugFontSize = 24;

        [Header("Toggler")]
        [InspectorLabel("Toggler Name")] public string debugTogglerName = "debug displayer";
        [KeyCodeListener] public KeyCode debugTogglerKey = KeyCode.None;

        [Header("Auto generation console message")]
        [InspectorLabel("Log")] public bool displayDebugGenerationMessage = true;
        [InspectorLabel("Message")] [TextArea(3, 5)] public string debugGenerationMessage = "Generated debug displayer. This only happens in the editor and dev build!";
        [InspectorLabel("Message Color")] public string debugGenerationMessageColor = "warning";

        [Header("Auto generation")]
        [InspectorLabel("Create In Editor")] public bool createDebugInEditor = true;
        [InspectorLabel("Create In Dev Build")] public bool createDebugInDeveloperBuild = true;
        [InspectorLabel("Create In Build")] public bool createDebugInBuild = false;

        public bool CreateDebugDisplayer
        {
            get
            {
#if UNITY_EDITOR
                return createDebugInEditor;
#else            
                return (Debug.isDebugBuild && createDebugInDeveloperBuild) || createDebugInBuild;
#endif

            }
        }
    }
}