using UnityEngine;

#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif

namespace qASIC.ProjectSettings
{
    [System.Serializable]
    [ExcludeFromPreset]
    public class DisplayerProjectSettings : ProjectSettingsBase
    {
        private static DisplayerProjectSettings _instance;
        public static DisplayerProjectSettings Instance => CheckInstance("Displayer", _instance);


        [InspectorLabel("Object Name")] public string debugObjectName = "Debug Displayer - autogenerated";
        [InspectorLabel("Displayer Name")] public string debugDisplayerName = "debug";

        [Header("Settings")]
        [InspectorLabel("Canvas Order")] public int debugCanvasOrder = 20;
        [InspectorLabel("Font size")] public int debugFontSize = 24;

        [Header("Toggler")]
        [InspectorLabel("Toggler Name")] public string debugTogglerName = "debug displayer";

        //----Debug Toggler Key----
#pragma warning disable CS0414

#if ENABLE_INPUT_SYSTEM
        [HideInInspector]
#endif
        [KeyCodeListener] [SerializeField] private KeyCode debugTogglerKey = KeyCode.None;
#if ENABLE_INPUT_SYSTEM
        [InspectorLabel("Debug Toggler Key")] [SerializeField] private Key debugTogglerKeyUIS = Key.None;
        public Key DebugTogglerKey { get => debugTogglerKeyUIS; set => debugTogglerKeyUIS = value; }
#else
        public KeyCode DebugTogglerKey { get => debugTogglerKey; set => debugTogglerKey = value; }
#endif

#pragma warning restore CS0414
        //-------------------------


        [Header("Auto generation console message")]
        [InspectorLabel("Log")] public bool displayDebugGenerationMessage = true;
        [InspectorLabel("Message")] [TextArea(3, 5)] public string debugGenerationMessage = "Generated debug displayer. This only happens in the editor and dev build!";
        [InspectorLabel("Message Color")] public string debugGenerationMessageColor = "warning";

        [Header("Auto generation")]
        [InspectorLabel("Create In Editor")] public bool createDebugInEditor = true;
        [InspectorLabel("Create In Dev Build")] public bool createDebugInDeveloperBuild = true;
        [InspectorLabel("Create In Build")] public bool createDebugInBuild = false;

        public bool CreateDebugDisplayer
        {
            get
            {
#if UNITY_EDITOR
                return createDebugInEditor;
#else
                return (Debug.isDebugBuild && createDebugInDeveloperBuild) || createDebugInBuild;
#endif

            }
        }
    }
}